// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofVGD7KjXe49mdM7v-_Dg8vG_H9nJfwE',
    appId: '1:449774334360:web:572c35b9f7c535bbe13bed',
    messagingSenderId: '449774334360',
    projectId: 'chat-app-8f250',
    authDomain: 'chat-app-8f250.firebaseapp.com',
    storageBucket: 'chat-app-8f250.appspot.com',
    measurementId: 'G-H4JZ9SN0QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgeqgMf8wo_Jxc9JNPrFU3lCt4NfRi9lo',
    appId: '1:449774334360:android:c5927fc304e6b423e13bed',
    messagingSenderId: '449774334360',
    projectId: 'chat-app-8f250',
    storageBucket: 'chat-app-8f250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfWlIb4uQWfYe6rGwt07fzmwnQ7hXYIE',
    appId: '1:449774334360:ios:89e823f84a2ec9e2e13bed',
    messagingSenderId: '449774334360',
    projectId: 'chat-app-8f250',
    storageBucket: 'chat-app-8f250.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkfWlIb4uQWfYe6rGwt07fzmwnQ7hXYIE',
    appId: '1:449774334360:ios:89e823f84a2ec9e2e13bed',
    messagingSenderId: '449774334360',
    projectId: 'chat-app-8f250',
    storageBucket: 'chat-app-8f250.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBofVGD7KjXe49mdM7v-_Dg8vG_H9nJfwE',
    appId: '1:449774334360:web:e4b20eaa41571ebde13bed',
    messagingSenderId: '449774334360',
    projectId: 'chat-app-8f250',
    authDomain: 'chat-app-8f250.firebaseapp.com',
    storageBucket: 'chat-app-8f250.appspot.com',
    measurementId: 'G-N1QFNDRVWS',
  );
}
